// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBd_A8i2QaaTa4_er-bFvf55DUnqy0No0U',
    appId: '1:342752663992:web:9482f75912c6537c1c974d',
    messagingSenderId: '342752663992',
    projectId: 'renconsport-d8097',
    authDomain: 'renconsport-d8097.firebaseapp.com',
    storageBucket: 'renconsport-d8097.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBsbkZGVQWQvK1MNvSzTjwFWnKYkMBJTnc',
    appId: '1:342752663992:android:e593f3556e267ea51c974d',
    messagingSenderId: '342752663992',
    projectId: 'renconsport-d8097',
    storageBucket: 'renconsport-d8097.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBpwGOj3a06g8JZDWts9ncXFsjiXA0XuD8',
    appId: '1:342752663992:ios:24607a938c89562f1c974d',
    messagingSenderId: '342752663992',
    projectId: 'renconsport-d8097',
    storageBucket: 'renconsport-d8097.appspot.com',
    iosBundleId: 'com.example.renconsportFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBpwGOj3a06g8JZDWts9ncXFsjiXA0XuD8',
    appId: '1:342752663992:ios:3954e86515e61b241c974d',
    messagingSenderId: '342752663992',
    projectId: 'renconsport-d8097',
    storageBucket: 'renconsport-d8097.appspot.com',
    iosBundleId: 'com.example.renconsportFlutter.RunnerTests',
  );
}
